cypress-io/schema-tools-master to rickydidaravong/schema-tools-master (#2)
* chore(deps): update semantic-release to 15.13.19 🌟

* chore(deps): update semantic-release to 15.13.21 🌟

* chore(deps): update ava to 2.3.0 🌟

* chore(deps): update @types/node to 9.6.51 🌟

* chore(deps): update tslint to 5.19.0 🌟

* chore(deps): update semantic-release to 15.13.24 🌟

* chore(deps): update tslint to 5.20.0 🌟

* chore(deps): update @types/node to 9.6.52 🌟

* chore(deps): update ava to 2.4.0 🌟

* chore(deps): update semantic-release to 15.13.27 🌟

* chore(deps): update @types/node to 9.6.53 🌟

* chore(deps): update semantic-release to 15.13.28 🌟

* chore(deps): update @types/node to 9.6.55 🌟

* chore(deps): update semantic-release to 15.13.29 🌟

* chore(deps): update semantic-release to 15.13.30 🌟

* chore(deps): update prettier to 1.19.0 🌟

* chore(deps): update prettier to 1.19.1 🌟

* feat: use d.ts rather than src/*.ts for typings (#295)

Allows us to ignore any type issues in this library
with skipLibCheck: true

* chore: Bump node version for semantic-release

* fix: add declaration property to generate .d.ts files

* chore(deps): update semantic-release to 15.13.31 🌟

* chore: fixed type errors. (#298)

* Changed the dependency versions to match cypress.

* Fixed type errors.

* chore(deps): update tslint to 5.20.1 🌟

* chore(deps): update typescript to 3.7.3 🌟

* chore(deps): update typescript to 3.7.4 🌟

* chore(deps): update semantic-release to 15.14.0 🌟

* fix: trigger release

* fix: move ramda types to production dependencies

In commit https://github.com/cypress-io/schema-tools/commit/8a667a283d37bf3e6401cb114051dc39838de064
we have started including ".d.ts" files with NPM package, which
generate comment `/// <reference types="ramda" />` which needs
TS definitions for Ramda library. So we must include the
`@types/ramda` in production dependencies, otherwise anyone using
our types from ".d.ts" gets missing type error like this one:

```
node_modules/@cypress/schema-tools/dist/api.d.ts:1:23
error TS2688: Cannot find type definition file for 'ramda'.
1 /// <reference types="ramda" />
```

* chore(deps): update typescript to 3.7.5 🌟

* chore(deps): update typescript to 3.8.2 🌟

* chore(deps): update typescript to 3.8.3 🌟

* chore(deps): update node to 8.17.0 🌟

Co-authored-by: Renovate Bot <bot@renovateapp.com>
Co-authored-by: Tim Griesser <tgriesser10@gmail.com>
Co-authored-by: Kukhyeon Heo <sainthkh@naver.com>
Co-authored-by: Jennifer Shehane <jennifer@cypress.io>
Co-authored-by: Gleb Bahmutov <gleb.bahmutov@gmail.com>